#! /bin/sh

# Kill any leftover XFCE window manager components
killall xfwm4 2>/dev/null &

#xwallpaper --zoom /home/testdesk/Pictures/walpapers/kita_fixed.jpg &

# increase touchpad acceleration speed
xinput set-prop "Elan Touchpad" "libinput Accel Speed" 0.4

# Detect and assign workspaces to your primary monitor
bspc monitor -d 1 2 3 4 5

# Window styling and behavior
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# Launch essential background services
sxhkd &
polybar main &

#redshift
redshift &

#(sleep 1 && DISPLAY=:0 feh --bg-scale /home/testdesk/Pictures/wallpapers/kita.png) &

(sleep 1 && ~/.fehbg) &
